// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateTestConsoleApp.CodeTemplates.EFCore
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Design;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Scaffolding;
    using Microsoft.Extensions.DependencyInjection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DbContext : DbContextBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 7 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
//paramStart
            
            #line default
            #line hidden
            
            #line 11 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
//paramEnd
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            this.Write("\r\n");
            
            #line 24 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"


    string StaticExtPropName = "ExtProp" ; // Json column using ef core 8 feature
    string DynamicExtPropName = "ExtPropBag" ; // Custom Json data using ToJson, works for earlier version of ef core

        //System.Diagnostics.Debugger.Launch(); 

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    if (!ProductInfo.GetVersion().StartsWith("8.0"))
    {
        Warning("Your templates were created using an older version of Entity Framework. Additional features and bug fixes may be available. See https://aka.ms/efcore-docs-updating-templates for more information.");
    }



    var services = (IServiceProvider)Host;
    var providerCode = services.GetRequiredService<IProviderConfigurationCodeGenerator>();
    var annotationCodeGenerator = services.GetRequiredService<IAnnotationCodeGenerator>();
    var code = services.GetRequiredService<ICSharpHelper>();

    var usings = new List<string>
    {
        "System",
        "System.Collections.Generic",
        "Microsoft.EntityFrameworkCore"
    };

    if (NamespaceHint != Options.ModelNamespace
        && !string.IsNullOrEmpty(Options.ModelNamespace))
    {
        usings.Add(Options.ModelNamespace);
    }

    if (!string.IsNullOrEmpty(NamespaceHint))
    {

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 61 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceHint));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 63 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }

            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 66 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.ContextName));
            
            #line default
            #line hidden
            this.Write(" : DbContext\r\n{\r\n");
            
            #line 68 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    if (!Options.SuppressOnConfiguring)
    {

            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 72 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.ContextName));
            
            #line default
            #line hidden
            this.Write("()\r\n    {\r\n    }\r\n\r\n");
            
            #line 76 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }

            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 79 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.ContextName));
            
            #line default
            #line hidden
            this.Write("(DbContextOptions<");
            
            #line 79 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.ContextName));
            
            #line default
            #line hidden
            this.Write("> options)\r\n        : base(options)\r\n    {\r\n    }\r\n\r\n");
            
            #line 84 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    foreach (var entityType in Model.GetEntityTypes().Where(e => !e.IsSimpleManyToManyJoinEntityType()))
    {

            
            #line default
            #line hidden
            this.Write("    public virtual DbSet<");
            
            #line 88 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityType.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 88 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityType.GetDbSetName()));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n");
            
            #line 90 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }

    if (!Options.SuppressOnConfiguring)
    {

            
            #line default
            #line hidden
            this.Write("    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)" +
                    "\r\n");
            
            #line 97 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    if (!Options.SuppressConnectionStringWarning)
    {

            
            #line default
            #line hidden
            this.Write(@"#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
");
            
            #line 102 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }

    var useProviderCall = providerCode.GenerateUseProvider(Options.ConnectionString);
    usings.AddRange(useProviderCall.GetRequiredUsings());

            
            #line default
            #line hidden
            this.Write("        => optionsBuilder");
            
            #line 108 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(useProviderCall, indent: 3)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 110 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }


            
            #line default
            #line hidden
            this.Write("    protected override void OnModelCreating(ModelBuilder modelBuilder)\r\n    {\r\n");
            
            #line 116 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    var anyConfiguration = false;

    var modelFluentApiCalls = Model.GetFluentApiCalls(annotationCodeGenerator);
    if (modelFluentApiCalls != null)
    {
        usings.AddRange(modelFluentApiCalls.GetRequiredUsings());

            
            #line default
            #line hidden
            this.Write("        modelBuilder");
            
            #line 124 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(modelFluentApiCalls, indent: 3)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 125 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

        anyConfiguration = true;
    }

    StringBuilder mainEnvironment;
    foreach (var entityType in Model.GetEntityTypes().Where(e => !e.IsSimpleManyToManyJoinEntityType()))
    {
        // Save all previously generated code, and start generating into a new temporary environment
        mainEnvironment = GenerationEnvironment;
        GenerationEnvironment = new StringBuilder();

        if (anyConfiguration)
        {
            WriteLine("");
        }

        var anyEntityTypeConfiguration = false;

            
            #line default
            #line hidden
            this.Write("        modelBuilder.Entity<");
            
            #line 143 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityType.Name));
            
            #line default
            #line hidden
            this.Write(">(entity =>\r\n        {\r\n");
            
            #line 145 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

        var key = entityType.FindPrimaryKey();
        if (key != null)
        {
            var keyFluentApiCalls = key.GetFluentApiCalls(annotationCodeGenerator);
            if (keyFluentApiCalls != null
                || (!key.IsHandledByConvention() && !Options.UseDataAnnotations))
            {
                if (keyFluentApiCalls != null)
                {
                    usings.AddRange(keyFluentApiCalls.GetRequiredUsings());
                }

            
            #line default
            #line hidden
            this.Write("            entity.HasKey(");
            
            #line 158 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Lambda(key.Properties, "e")));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 158 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(keyFluentApiCalls, indent: 4)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 159 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

                anyEntityTypeConfiguration = true;
            }
        }

        var entityTypeFluentApiCalls = entityType.GetFluentApiCalls(annotationCodeGenerator)
            ?.FilterChain(c => !(Options.UseDataAnnotations && c.IsHandledByDataAnnotations));
        if (entityTypeFluentApiCalls != null)
        {
            usings.AddRange(entityTypeFluentApiCalls.GetRequiredUsings());

            if (anyEntityTypeConfiguration)
            {
                WriteLine("");
            }

            
            #line default
            #line hidden
            this.Write("            entity");
            
            #line 175 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(entityTypeFluentApiCalls, indent: 4)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 176 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            anyEntityTypeConfiguration = true;
        }

        foreach (var index in entityType.GetIndexes()
            .Where(i => !(Options.UseDataAnnotations && i.IsHandledByDataAnnotations(annotationCodeGenerator))))
        {
            if (anyEntityTypeConfiguration)
            {
                WriteLine("");
            }

            var indexFluentApiCalls = index.GetFluentApiCalls(annotationCodeGenerator);
            if (indexFluentApiCalls != null)
            {
                usings.AddRange(indexFluentApiCalls.GetRequiredUsings());
            }

            
            #line default
            #line hidden
            this.Write("            entity.HasIndex(");
            
            #line 194 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Lambda(index.Properties, "e")));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 194 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Literal(index.GetDatabaseName())));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 194 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(indexFluentApiCalls, indent: 4)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 195 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            anyEntityTypeConfiguration = true;
        }

        var firstProperty = true;
        foreach (var property in entityType.GetProperties())
        {
            if ( property.Name  == StaticExtPropName) 
                continue ;
            if ( property.Name  == DynamicExtPropName) 
                continue ;
            //foreach ( var config in UseConfigure )
            //    if ( property.Name  == config) 
            //        continue ;

            var propertyFluentApiCalls = property.GetFluentApiCalls(annotationCodeGenerator)
                ?.FilterChain(c => !(Options.UseDataAnnotations && c.IsHandledByDataAnnotations)
                    && !(c.Method == "IsRequired" && Options.UseNullableReferenceTypes && !property.ClrType.IsValueType));
            if (propertyFluentApiCalls == null)
            {
                continue;
            }

            usings.AddRange(propertyFluentApiCalls.GetRequiredUsings());

            if (anyEntityTypeConfiguration && firstProperty)
            {
                WriteLine("");
            }

            
            #line default
            #line hidden
            this.Write("            entity.Property(e => e.");
            
            #line 225 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 225 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(propertyFluentApiCalls, indent: 4)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 226 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            anyEntityTypeConfiguration = true;
            firstProperty = false;
        }

        foreach (var foreignKey in entityType.GetForeignKeys())
        {
            var foreignKeyFluentApiCalls = foreignKey.GetFluentApiCalls(annotationCodeGenerator)
                ?.FilterChain(c => !(Options.UseDataAnnotations && c.IsHandledByDataAnnotations));
            if (foreignKeyFluentApiCalls == null)
            {
                continue;
            }

            usings.AddRange(foreignKeyFluentApiCalls.GetRequiredUsings());

            if (anyEntityTypeConfiguration)
            {
                WriteLine("");
            }

            
            #line default
            #line hidden
            this.Write("            entity.HasOne(d => d.");
            
            #line 247 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.DependentToPrincipal.Name));
            
            #line default
            #line hidden
            this.Write(").");
            
            #line 247 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.IsUnique ? "WithOne" : "WithMany"));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 247 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.PrincipalToDependent != null ? $"p => p.{foreignKey.PrincipalToDependent.Name}" : ""));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 247 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(foreignKeyFluentApiCalls, indent: 4)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 248 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            anyEntityTypeConfiguration = true;
        }

        foreach (var skipNavigation in entityType.GetSkipNavigations().Where(n => n.IsLeftNavigation()))
        {
            if (anyEntityTypeConfiguration)
            {
                WriteLine("");
            }

            var left = skipNavigation.ForeignKey;
            var leftFluentApiCalls = left.GetFluentApiCalls(annotationCodeGenerator, useStrings: true);
            var right = skipNavigation.Inverse.ForeignKey;
            var rightFluentApiCalls = right.GetFluentApiCalls(annotationCodeGenerator, useStrings: true);
            var joinEntityType = skipNavigation.JoinEntityType;

            if (leftFluentApiCalls != null)
            {
                usings.AddRange(leftFluentApiCalls.GetRequiredUsings());
            }

            if (rightFluentApiCalls != null)
            {
                usings.AddRange(rightFluentApiCalls.GetRequiredUsings());
            }

            
            #line default
            #line hidden
            this.Write("            entity.HasMany(d => d.");
            
            #line 275 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(skipNavigation.Name));
            
            #line default
            #line hidden
            this.Write(").WithMany(p => p.");
            
            #line 275 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(skipNavigation.Inverse.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n                .UsingEntity<Dictionary<string, object>>(\r\n                   " +
                    " ");
            
            #line 277 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Literal(joinEntityType.Name)));
            
            #line default
            #line hidden
            this.Write(",\r\n                    r => r.HasOne<");
            
            #line 278 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(right.PrincipalEntityType.Name));
            
            #line default
            #line hidden
            this.Write(">().WithMany()");
            
            #line 278 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(rightFluentApiCalls, indent: 6)));
            
            #line default
            #line hidden
            this.Write(",\r\n                    l => l.HasOne<");
            
            #line 279 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(left.PrincipalEntityType.Name));
            
            #line default
            #line hidden
            this.Write(">().WithMany()");
            
            #line 279 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(leftFluentApiCalls, indent: 6)));
            
            #line default
            #line hidden
            this.Write(",\r\n                    j =>\r\n                    {\r\n");
            
            #line 282 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            var joinKey = joinEntityType.FindPrimaryKey();
            var joinKeyFluentApiCalls = joinKey.GetFluentApiCalls(annotationCodeGenerator);

            if (joinKeyFluentApiCalls != null)
            {
                usings.AddRange(joinKeyFluentApiCalls.GetRequiredUsings());
            }

            
            #line default
            #line hidden
            this.Write("                        j.HasKey(");
            
            #line 291 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Arguments(joinKey.Properties.Select(e => e.Name))));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 291 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(joinKeyFluentApiCalls, indent: 7)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 292 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            var joinEntityTypeFluentApiCalls = joinEntityType.GetFluentApiCalls(annotationCodeGenerator);
            if (joinEntityTypeFluentApiCalls != null)
            {
                usings.AddRange(joinEntityTypeFluentApiCalls.GetRequiredUsings());

            
            #line default
            #line hidden
            this.Write("                        j");
            
            #line 298 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(joinEntityTypeFluentApiCalls, indent: 7)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 299 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            }

            foreach (var index in joinEntityType.GetIndexes())
            {
                var indexFluentApiCalls = index.GetFluentApiCalls(annotationCodeGenerator);
                if (indexFluentApiCalls != null)
                {
                    usings.AddRange(indexFluentApiCalls.GetRequiredUsings());
                }

            
            #line default
            #line hidden
            this.Write("                        j.HasIndex(");
            
            #line 310 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Literal(index.Properties.Select(e => e.Name).ToArray())));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 310 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Literal(index.GetDatabaseName())));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 310 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(indexFluentApiCalls, indent: 7)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 311 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            }

            foreach (var property in joinEntityType.GetProperties())
            {
                var propertyFluentApiCalls = property.GetFluentApiCalls(annotationCodeGenerator);
                if (propertyFluentApiCalls == null)
                {
                    continue;
                }

                usings.AddRange(propertyFluentApiCalls.GetRequiredUsings());

            
            #line default
            #line hidden
            this.Write("                        j.IndexerProperty<");
            
            #line 324 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Reference(property.ClrType)));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 324 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Literal(property.Name)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 324 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(propertyFluentApiCalls, indent: 7)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 325 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            }

            
            #line default
            #line hidden
            this.Write("                    });\r\n");
            
            #line 329 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

            anyEntityTypeConfiguration = true;
        }

            
            #line default
            #line hidden
            this.Write("        });\r\n");
            
            #line 334 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

        // If any signicant code was generated, append it to the main environment
        if (anyEntityTypeConfiguration)
        {
            mainEnvironment.Append(GenerationEnvironment);
            anyConfiguration = true;
        }

        // Resume generating code into the main environment
        GenerationEnvironment = mainEnvironment;
    }

    foreach (var sequence in Model.GetSequences())
    {
        var needsType = sequence.Type != typeof(long);
        var needsSchema = !string.IsNullOrEmpty(sequence.Schema) && sequence.Schema != sequence.Model.GetDefaultSchema();
        var sequenceFluentApiCalls = sequence.GetFluentApiCalls(annotationCodeGenerator);

            
            #line default
            #line hidden
            this.Write("        modelBuilder.HasSequence");
            
            #line 352 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(needsType ? $"<{code.Reference(sequence.Type)}>" : ""));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 352 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Literal(sequence.Name)));
            
            #line default
            #line hidden
            
            #line 352 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(needsSchema ? $", {code.Literal(sequence.Schema)}" : ""));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 352 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(code.Fragment(sequenceFluentApiCalls, indent: 3)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 353 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }

    if (anyConfiguration)
    {
        WriteLine("");
    }

            
            #line default
            #line hidden
            this.Write("        OnModelCreatingPartial(modelBuilder);\r\n    }\r\n\r\n    partial void OnModelC" +
                    "reatingPartial(ModelBuilder modelBuilder);\r\n}\r\n");
            
            #line 366 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    mainEnvironment = GenerationEnvironment;
    GenerationEnvironment = new StringBuilder();

    foreach (var ns in usings.Distinct().OrderBy(x => x, new NamespaceComparer()))
    {

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 373 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 374 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

    }

    WriteLine("");

    GenerationEnvironment.Append(mainEnvironment);

            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 384 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"


Microsoft.EntityFrameworkCore.Metadata.IModel Model ;
Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions Options ;
System.String NamespaceHint ;




        
        #line default
        #line hidden
        
        #line 1 "U:\EFTemplate\TemplateTestConsoleApp\CodeTemplates\EFCore\DbContext.t4"

private global::Microsoft.EntityFrameworkCore.Metadata.IModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::Microsoft.EntityFrameworkCore.Metadata.IModel Model
{
    get
    {
        return this._ModelField;
    }
}

private global::Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions _OptionsField;

/// <summary>
/// Access the Options parameter of the template.
/// </summary>
private global::Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions Options
{
    get
    {
        return this._OptionsField;
    }
}

private string _NamespaceHintField;

/// <summary>
/// Access the NamespaceHint parameter of the template.
/// </summary>
private string NamespaceHint
{
    get
    {
        return this._NamespaceHintField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::Microsoft.EntityFrameworkCore.Metadata.IModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Model");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::Microsoft.EntityFrameworkCore.Metadata.IModel));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._ModelField = ((global::Microsoft.EntityFrameworkCore.Metadata.IModel)(tc.ConvertFrom(parameterValue)));
            ModelValueAcquired = true;
        }
        else
        {
            this.Error("The type \'Microsoft.EntityFrameworkCore.Metadata.IModel\' of the parameter \'Model\'" +
                    " did not match the type of the data passed to the template.");
        }
    }
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::Microsoft.EntityFrameworkCore.Metadata.IModel)(data));
    }
}
bool OptionsValueAcquired = false;
if (this.Session.ContainsKey("Options"))
{
    this._OptionsField = ((global::Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions)(this.Session["Options"]));
    OptionsValueAcquired = true;
}
if ((OptionsValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Options");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._OptionsField = ((global::Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions)(tc.ConvertFrom(parameterValue)));
            OptionsValueAcquired = true;
        }
        else
        {
            this.Error("The type \'Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions\' o" +
                    "f the parameter \'Options\' did not match the type of the data passed to the templ" +
                    "ate.");
        }
    }
}
if ((OptionsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Options");
    if ((data != null))
    {
        this._OptionsField = ((global::Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions)(data));
    }
}
bool NamespaceHintValueAcquired = false;
if (this.Session.ContainsKey("NamespaceHint"))
{
    this._NamespaceHintField = ((string)(this.Session["NamespaceHint"]));
    NamespaceHintValueAcquired = true;
}
if ((NamespaceHintValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "NamespaceHint");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(string));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._NamespaceHintField = ((string)(tc.ConvertFrom(parameterValue)));
            NamespaceHintValueAcquired = true;
        }
        else
        {
            this.Error("The type \'System.String\' of the parameter \'NamespaceHint\' did not match the type " +
                    "of the data passed to the template.");
        }
    }
}
if ((NamespaceHintValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("NamespaceHint");
    if ((data != null))
    {
        this._NamespaceHintField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class DbContextBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
